fixtures:
  forge_modules:
    stdlib: 'puppetlabs/stdlib'
    archive:
      repo: 'puppet/archive'
    apt:
      repo: 'puppetlabs/apt'
    mongodb:
      repo: 'puppet/mongodb'
    nodejs:
      repo: 'puppet/nodejs'
